application: snippet-profiler
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: static/index.htm
  upload: static/index.htm

- url: /api-1/.*
  script: snip.main.application

- url: /
  static_dir: static/
